# Generated by Django 5.2.6 on 2025-09-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_desc', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
            ],
        ),
    ]
